import {Inter} from '@next/font/google';
import Head from 'next/head';
import Footer from '../components/footer';
import Header from '../components/header';

const inter = Inter({subsets:["latin"],weight:"400"});
export default function Layout({children}){
    return (
        <>
            <Head>
            <title>Uganda National Council For Higher Education | Journal</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            </Head>
            <main className={`${inter.className} page-wrapper`}>
                <Header/>
                {children}
            </main>
            {/* <Footer/> */}
        </>
    );
}